### ISSUE TITLE
[Docs] creating the contribution.md file.

### ISSUE THREAD

**Issue by 1Shubham7** [1Shubham7/Wife-Predictor-v2#10]
The repo doesn't have a readme.md file, We can create one.

**Comment by SrNightmare09** [comment]
i think this issue has been solved

**Comment by 1Shubham7** [comment]
ok. Assigning it to you.

**Comment by SrNightmare09** [comment]
@1Shubham7 I meant that the Readme  for this repository has already been created. So because of that this issue should be closed.

**Comment by 1Shubham7** [comment]
sorry I misunderstood your point.

**Comment by 1Shubham7** [comment]
I think we will need a contibution.md file now or later once the project gets more complicated. Let's not close the issue.
