### ISSUE TITLE
missing Confetti effect

### ISSUE THREAD

**Issue by paulkrishanu4** [1Shubham7/Wife-Predictor-v2#110]
I think there should a confetti animation as the wife appears , assign me this task under gssoc'24

![confitti effect](https://github.com/1Shubham7/Wife-Predictor-v2/assets/169196836/038e4cc5-f469-4156-b363-e00a3d34b6cf)

**Comment by 1Shubham7** [comment]
nice idea, we can have this when we see the wife image. Please go ahead.
