### ISSUE TITLE
Spacing is required in how can you help para

### ISSUE THREAD

**Issue by kapilG0** [1Shubham7/Wife-Predictor-v2#111]
Before email spacing is required 
![Screenshot_20240514_160922](https://github.com/1Shubham7/Wife-Predictor-v2/assets/59639410/94800545-c53a-478e-a4f4-25dffbbc5040)

**Comment by kapilG0** [comment]
Hello @1Shubham7 please assign this issue to me under gssoc 24

**Comment by 1Shubham7** [comment]
fixed already.
