### ISSUE TITLE
Add age field in the play screen

### ISSUE THREAD

**Issue by jumankaushik** [1Shubham7/Wife-Predictor-v2#131]
I will add a age field under name so that only above 18 can play and start the game only the cases are passed. 
![{AA617FBA-EB0B-4451-9E53-AEFE283ADC1F}](https://github.com/user-attachments/assets/583c24b9-b171-4df6-b46b-0090080ce24e)

**Comment by 1Shubham7** [comment]
I don't think that is needed, but thanks for the suggestion: )
