### ISSUE TITLE
Add a title above the wife image

### ISSUE THREAD

**Issue by jumankaushik** [1Shubham7/Wife-Predictor-v2#132]
Add a title above the wife photo saying "XYZ, your future wife is" which will make it more dynamic and cool. 
For eg., if my input is Raju, then it will say "Raju, your future wife is"

![image](https://github.com/user-attachments/assets/7e2c80ba-c888-4576-964d-b8efa80171b7)

Kindly assign it under GSSOC and hacktoberfest. Thank you

**Comment by 1Shubham7** [comment]
great, I think you should go ahead and implement the point  2 first and open another issue for point 1 : )

**Comment by jumankaushik** [comment]
Okay on it. Kindly assign under GSSOC and hacktoberfest

**Comment by SaanyaGarg5** [comment]
you can assign that task to me under gsso-ext and Hacktoberfest label..

**Comment by jumankaushik** [comment]
Hey @1Shubham7 , it is done and I will send the PR in a while. Assign it under GSSOC-ext and hacktoberfest. 

and @SaanyaGarg5 , this issue has already been assigned to me, so you can create your own issue or you can work on other issue which has not been assigned to anyone yet :)

**Comment by 1Shubham7** [comment]
change the issue name and discription to be about about adding that title, you can add another PR for other stuff : )

**Comment by jumankaushik** [comment]
Done :)

**Comment by jumankaushik** [comment]
Hey @1Shubham7 , Please add the label of specifically **gssoc-ext**, **hacktoberfest-accepted**, **hacktoberfest** in the issue also.. otherwise it will not be counted :)
