### ISSUE TITLE
ENHANCING THE USER INRERFACE (FONTS, COLORS, BARS, EFFECTS ,EFFECTS)

### ISSUE THREAD

**Issue by dnyanesh99borse** [1Shubham7/Wife-Predictor-v2#135]
**### ENHANCING THE USER INRERFACE (FONTS, COLORS, BARS, EFFECTS ,EFFECTS)**

**I can enhance the whole user interface of the main user landing page and can make it very attractive by managing it's fonts, colors, effects and much more with interating and functioning interface**

**Comment by dnyanesh99borse** [comment]
AS A EXPERIENCED FRONTEND DEVELOPER I CAN SAY THAT I CAN INSERT THE NEW SOUL TO THE WHOLE WEBSITE LANDING PAGE AND CAN MAKE IT VERY ATTRACTIVE SO THE USERS WILL SPEND MOST OF THE TIME ON THE WEBSITE. . SO I HUMBLY REQUSET YOU TO PLEASE ASSIGN THIS TASK TO ME .

**Comment by 1Shubham7** [comment]
hey @dnyanesh99borse, you have to be specific in your issue, you can't change entire UI in one issue : )

**Comment by SaanyaGarg5** [comment]
you can assign that task to me under gsso-ext and Hacktoberfest label..
