### ISSUE TITLE
Suggestion to Improve "Predict Future Wife" Feature

### ISSUE THREAD

**Issue by GitWizzz** [1Shubham7/Wife-Predictor-v2#137]
I wanted to suggest a small improvement for the "Predict Future Wife" feature in the project. Currently, after using the prediction feature, the result is displayed correctly, but there is no button or option for users to try again. Adding a "Try Again" button would enhance the user experience, making it more interactive and engaging.

**Comment by 1Shubham7** [comment]
already people working on it : )

**Comment by GitWizzz** [comment]
> I wanted to suggest a small improvement for the "Predict Future Wife" feature in the project. Currently, after using the prediction feature, the result is displayed correctly, but there is no button or option for users to try again. Adding a "Try Again" button would enhance the user experience, making it more interactive and engaging.

i have been forgotten to add labels regarding gssoc and hacktober
