### ISSUE TITLE
Create a GitHub action for thanking contributors once there request is merged

### ISSUE THREAD

**Issue by 1Shubham7** [1Shubham7/Wife-Predictor-v2#138]
![image](https://github.com/user-attachments/assets/3c5b17b4-f4b9-4bb7-a60a-455fe3daeba2)

I think we can have a github action that would thank contributors like this once their PR is merged.

**Comment by ShehzadAhm** [comment]
Hi @1Shubham7, can I pick this issue?

**Comment by 1Shubham7** [comment]
sure, please go ahead. Hopefully you will implement this within this week : )

**Comment by ShehzadAhm** [comment]
Hi @1Shubham7, PR created - https://github.com/1Shubham7/Wife-Predictor-v2/pull/144

**Comment by ShehzadAhm** [comment]
Hi @1Shubham7, there was a minor typo - PR https://github.com/1Shubham7/Wife-Predictor-v2/pull/149
