### ISSUE TITLE
docs: update installation instructions

### ISSUE THREAD

**Issue by SrNightmare09** [1Shubham7/Wife-Predictor-v2#14]
In the documentation, one step before running `npm start` should be running `npm install`, because otherwise the user receives an error such as the following

![image](https://github.com/1Shubham7/Wife-Predictor-v2/assets/73314216/e185fa9d-8496-488c-9320-6fdb2a1bb0be)

**Comment by SrNightmare09** [comment]
If you wish, I can contribute by making a better README for the project.

**Comment by 1Shubham7** [comment]
@SrNightmare09 , I would love your participation. The steps in readme are wrong. Please correct them and also add images (view count, stars of repo etc etc ) to make it look better.

**Comment by 1Shubham7** [comment]
All the best @SrNightmare09 . Do star the repo as well. It would really help!

**Comment by 1Shubham7** [comment]
Thank you @SrNightmare09 . I really appreciate your contribution.
