### ISSUE TITLE
Alter database object to be an array

### ISSUE THREAD

**Issue by theQuery** [1Shubham7/Wife-Predictor-v2#18]
I believe the database object would be easier maintainable if it was an array instead of an object. That way the keys (numbers) wouldn't need to be added for each picture object added. It's also how it would be structured if it was fetched from a database. See example below:

```diff
- const womendata = {
-     1: { id: 1, ...more },
-     2: { id: 2, ...more }
- };

+ const womendata = [
+     { id: 1, ...more },
+     { id: 2, ...more }
+ ];
```

**Comment by 1Shubham7** [comment]
fine. I am open to it! go ahead
