### ISSUE TITLE
Change generatorRandomNumber()

### ISSUE THREAD

**Issue by theQuery** [1Shubham7/Wife-Predictor-v2#21]
Change generatorRandomNumber() in Confirm.js to be based on the length of the wives array instead of a hardcoded number. That way it won't have to be changed with each image added to the wives array.

```diff
 function generatorRandomNumber() {
-    return Math.floor(Math.random() * 40);
+    return Math.floor(Math.random() * wives.length);
 }
```

**Comment by 1Shubham7** [comment]
LGTM, go ahead!
