### ISSUE TITLE
website needs improvement in texts and adding some visual items

### ISSUE THREAD

**Issue by 1Shubham7** [1Shubham7/Wife-Predictor-v2#28]

**Comment by anubhav1206** [comment]
Can I work on this?

**Comment by 1Shubham7** [comment]
yes, @anubhav1206.

**Comment by Gokilp** [comment]
please assign to me #gssoc24

**Comment by its-kumar-yash** [comment]
Hey @1Shubham7, I would like to work on this issue, Kindly Assign this to me

**Comment by Ajita369** [comment]
Can you please assign this issue to me?

**Comment by Nih1tGupta** [comment]
Can you please assign this issue to me?

**Comment by Praneeth2312** [comment]
can you please assign this to me!and mark it for GSSOC

**Comment by sahithinandikula** [comment]
@1Shubham7 I can add some fantastic fonts and also adding some background images will look better. I am interested in working on this issue.

**Comment by Priii-13** [comment]
@1Shubham7 please assign this issue to me.

**Comment by sanjogbhalla16** [comment]
@1Shubham7 , if its still open please assign this issue to me under the tage hacktoberfest,thank you
