### ISSUE TITLE
There is no hyperlink for installing Node.js in README.md file

### ISSUE THREAD

**Issue by dhanyashreem2400** [1Shubham7/Wife-Predictor-v2#45]
**While setting up locally, at step 0 there is no hyperlink for installing Node.js in README.md file.** 

![Screenshot (87)](https://github.com/1Shubham7/Wife-Predictor-v2/assets/97956917/7eac32e9-289d-4ea8-b039-2fb7b32de276)

**Comment by 1Shubham7** [comment]
But we are not using node js in the project.
