### ISSUE TITLE
Fixing the Size for Header

### ISSUE THREAD

**Issue by prafulnigam** [1Shubham7/Wife-Predictor-v2#54]
![image](https://github.com/1Shubham7/Wife-Predictor-v2/assets/78497704/00264d47-97a0-476b-85b0-0f6f8b3e1b6b)

**Comment by prafulnigam** [comment]
I am Praful Nigam. Under GSSOC'24, I would like to work on this issue. Pls assign me this!!

**Comment by Anup2601** [comment]
I would like to work on this issue, please assign this issue to me under GSSoC'24.
