### ISSUE TITLE
Remove the grammatical mistakes in the website.

### ISSUE THREAD

**Issue by 1Shubham7** [1Shubham7/Wife-Predictor-v2#6]
The website and the readme.md file has a lot of grammatical mistakes. Please correct them.

**Comment by theQuery** [comment]
I'd like to be assigned this task

**Comment by 1Shubham7** [comment]
ok sure.

**Comment by theQuery** [comment]
Thank you!

**Comment by 1Shubham7** [comment]
@theQuery , I can't merge your PR, it is too big. The website will go offline. Please make small changes and do small PR. Would you want to do it again.

**Comment by theQuery** [comment]
How small should the PRs be? One per file?

**Comment by 1Shubham7** [comment]
yup.

**Comment by theQuery** [comment]
I believe it should be okay to merge them all at once, though? If it's deployed on Netlify as it says that it is, then there shouldn't be any downtime to worry about.

**Comment by 1Shubham7** [comment]
@theQuery . Yup , you are right. It had some conflicts but I resolved them. Thank you for contributing. Do contribute more. your contributions are highly appreciated.

**Comment by 1Shubham7** [comment]
Do give the repo a star!!

**Comment by theQuery** [comment]
It's my pleasure! I'll make sure to star it as well
