### ISSUE TITLE
Re-alignment Of Mobile View....

### ISSUE THREAD

**Issue by Pratham-Vishwakarma** [1Shubham7/Wife-Predictor-v2#65]
I found That the Mobile Site for this project is not properly aligned with "What's your name?". I can fix that for you. Please label me under Gssoc'24.

![WhatsApp Image 2024-05-11 at 1 53 30 PM](https://github.com/1Shubham7/Wife-Predictor-v2/assets/147902380/79512034-27d0-4638-9b98-2d5907a983b8)

**Comment by 1Shubham7** [comment]
go ahead.

**Comment by KavyaBS123** [comment]
Hey @1Shubham7 I am GSSOC contributor I would like to work on this can you please assign this issue to me!

**Comment by Pratham-Vishwakarma** [comment]
I Have Done My Task. Thank You

**Comment by Pratham-Vishwakarma** [comment]
Hello, Please label the level of this issue. for Gssoc'24. Thank You
