### ISSUE TITLE
Let's Add Some Voice Notes To Make It Funnier...

### ISSUE THREAD

**Issue by Pratham-Vishwakarma** [1Shubham7/Wife-Predictor-v2#68]
I Would like **To Add Voice Notes**, it will make this game more fun and interactive. I was thinking I could use some Voice Mods and
and my voice to make it fun but keeping the code of conducts in mind.What Do You Think??? 

Please Label me under Gssoc'24 and assign me this task.

**Comment by 1Shubham7** [comment]
I don't think we should do that right now...

**Comment by Pratham-Vishwakarma** [comment]
Why not,I think it will be fun
