### ISSUE TITLE
Improving the UI header for this website

### ISSUE THREAD

**Issue by Unalia09** [1Shubham7/Wife-Predictor-v2#72]
I'd like to recommend some UI changes for the header section

![image](https://github.com/1Shubham7/Wife-Predictor-v2/assets/147930477/bf3a747d-fdfe-46be-9709-d31fd6f581a4)

**Comment by Unalia09** [comment]
Please assign this task to me under GSSoC

**Comment by sweta123761** [comment]
assign that to me

**Comment by Trumilnasit** [comment]
@Unalia09 Can you assign it to me i would like to contribute in it... and also firstly please adds some labels like GSSoc2024 , hactoberfest and etc.. to it will help a lot us in leaderboard.

**Comment by 1Shubham7** [comment]
I don't think this is needed : ) but thanks for your suggestion guys : )
