### ISSUE TITLE
[Feature] Linkedin Handle and About Us links are broken

### ISSUE THREAD

**Issue by Ayush170803** [1Shubham7/Wife-Predictor-v2#73]
Linkedin Handle are not redirecting to the mentioned handle and About us links are also broken. so kindly provide the social media account and about us website link to fix this issue. Kindly assign me this issue, so i can work towards it under GSSOC'24. Thank You

https://github.com/1Shubham7/Wife-Predictor-v2/assets/115927008/a3e1fd75-cf41-4875-8053-3153a2394ff7

**Comment by Ayush170803** [comment]
Kindly assign me this issue, so i can work towards it under GSSoC'24. Thank You @1Shubham7

**Comment by 1Shubham7** [comment]
Already been fixed
