### ISSUE TITLE
Add Dark mode feature

### ISSUE THREAD

**Issue by tat-tvam-asii** [1Shubham7/Wife-Predictor-v2#78]
I would like to add dark mode feature to the website. Please assign me under tags : gssoc'24 , level2

**Comment by JanitKumar** [comment]
@tat-tvam-asii  please assign this issue to me under gssoc24. I want to eagerly contribute on this I have proper skills to do the assigned work.

**Comment by KavyaBS123** [comment]
Hey @1Shubham7 I am GSSOC Contributor can you please assign this issue as GSSOC and assign this issue to me I would love to work on this!

**Comment by tat-tvam-asii** [comment]
@1Shubham7 Please respond
