### ISSUE TITLE
Adding Feedback/Contact us page with form for users

### ISSUE THREAD

**Issue by Suvam3456** [1Shubham7/Wife-Predictor-v2#81]
The Website lacks Contact us Page through which users of Website interact with Project Owner.

Describe the solution you'd like
I'll make an attractive Contact us form where users can send their reactions/feedback by adding their name and email and , it will be a working form and admin will recieve notifiactions on his email for every user reaction.

An example is below:

![image](https://github.com/1Shubham7/Wife-Predictor-v2/assets/99579881/c2128a70-9e16-4884-84d1-bde8bc9b36e0)

I can improve UI further if you want.

Assign me this under GSSOC'24.

**Comment by Suvam3456** [comment]
@1Shubham7 Assign me above issue

**Comment by 1Shubham7** [comment]
Good Idea!

**Comment by krati234** [comment]
i would like to work on it , please assign me this issue

**Comment by Suvam3456** [comment]
@1Shubham7 I have raised a PR for this issue.

**Comment by Suvam3456** [comment]
@1Shubham7 Please add label of level to my PR
