### ISSUE TITLE
About page not working

### ISSUE THREAD

**Issue by AkhilaSunesh** [1Shubham7/Wife-Predictor-v2#86]
![image](https://github.com/1Shubham7/Wife-Predictor-v2/assets/140897461/c8f96bd7-8555-4048-8b27-7eacc7615ca3)

**About:** There is no proper description on this topic.
**Result:** Making it difficult for users to understand the functionality

### Allow me to solve this issue. Kindly pay heed to this issue.

**Comment by bk408** [comment]
I would like to take responsibility for this issue. Please assign it to me.
