### ISSUE TITLE
Website needs a heder with name and logo of website

### ISSUE THREAD

**Issue by Coder-Kartikey** [1Shubham7/Wife-Predictor-v2#91]
🎮 feature Request
Website needs a heder with name and logo of website.

My Header will have:
      Logo
      Website name
      About Us 
     Contact Us 
I will make the header responsive so it will work properly in all devices.
Assign this to me under GSSoC'24.

**Comment by Coder-Kartikey** [comment]
@1Shubham7, Please assign this task to me under GSSoC'24

**Comment by SaanyaGarg5** [comment]
you can assign that task to me under gsso-ext and Hacktoberfest label..

**Comment by clownfish1805** [comment]
@1Shubham7 I would like to work on this issue.
Please assign me under Hacktoberfest and GSSOC'24 extended.
