### ISSUE TITLE
Add Topics

### ISSUE THREAD

**Issue by Princegupta101** [1Shubham7/Wife-Predictor-v2#92]
In GSSoC'24, GitHub Topics will help the discoverability of your project.

I see that you already have great topics on your repository!
I would recommend adding the name of the company like the software you use to build like "vs-code, ghdesktop" to improve your discoverability.

If you are happy with the topics you have, feel free to close this issue. 👍

**Comment by 1Shubham7** [comment]
GitHub Topics sounds interesting, but I haven't used it. Please ellaborate on the process of doing it, or you can raise a PR for that.

**Comment by SaanyaGarg5** [comment]
you can assign that task to me under gsso-ext and Hacktoberfest label..
