### ISSUE TITLE
Typo in how can you help section

### ISSUE THREAD

**Issue by aditijha-123** [1Shubham7/Wife-Predictor-v2#98]
Typo Screenshot : 

![error](https://github.com/1Shubham7/Wife-Predictor-v2/assets/138472894/ccaa9c0a-060f-44af-86e0-b7f4b4961957)

Issue : There is no space between my and email in the second line.

Possible Fix :  Before -  "myemail"  
                      After    -  "my email" 

@1Shubham7 please assign this issue to me under GSSOC'24

**Comment by 1Shubham7** [comment]
already fixed.
